import Head from 'next/head';
import Image from 'next/image';
import AboutMe from '../components/AboutMe';
import ContactMe from '../components/ContactMe';
import Intro from '../components/Intro';
import Projects from '../components/Projects';
import Skills from '../components/Skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gustavo Allen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/helpme.ico" />
      </Head>
      <h1 className="">Hello World</h1>
      {/* <Intro /> */}
      {/* <Skills /> */}
      <Projects />
      {/* <AboutMe /> */}
      {/* <ContactMe /> */}
      <a target="_blank" href="https://icons8.com/icon/114116/source-code">
        Source Code
      </a>{' '}
      icon by{' '}
      <a target="_blank" href="https://icons8.com">
        Icons8
      </a>
    </div>
  );
}
